micronaut.application.name=search-service
micronaut.server.port=8082
micronaut.serde.serialization.inclusion=NON_NULL
micronaut.router.static-resources.default.enabled=true
micronaut.router.static-resources.default.mapping=/**
micronaut.router.static-resources.default.paths=classpath:public

opensearch.url=http://localhost:9200
opensearch.index=news_article

embedding.provider=${EMBEDDING_PROVIDER:openai}
embedding.dimensions=${EMBEDDING_DIMENSIONS:384}
embedding.model=${EMBEDDING_MODEL:text-embedding-3-small}
